# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Nikitid
charon {
	install_routes = no
	install_virtual_ip = no
	retry_initiate_interval = 15s
	plugins {
		kernel-netlink {
			install_routes_xfrmi = no
		}
	}
}
