#!/bin/sh
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Nikitid
#
# template: gen-index v4 (repo-templates)
# Formatted with `shfmt -i 2 -bn -ci` so it passes the strictest consumer;
# a repository whose own style differs still gets this file verbatim.
# Do not edit in place: change templates/shared/ in repo-templates
# and run scripts/sync-templates.sh --update.
#
# Generate docs/INDEX.md: every function in every source file large enough that
# reading it whole is wasteful, with its line number and its own first comment
# line as the purpose.
#
# The point is not to be read end to end. It is to be grepped:
#
#     grep -n <function name> docs/INDEX.md
#
# which answers "where does this live" in three lines instead of the thirty
# thousand tokens it costs to read one of the big files.
#
# scripts/check-index.sh regenerates this and fails when the committed copy has
# drifted, so the map cannot rot without the build noticing.

set -eu

root="$(CDPATH='' cd -- "$(dirname "$0")/.." && pwd)"
out="${1:-$root/docs/INDEX.md}"
min_lines=300

cd "$root"

# Linear test scripts have no functions worth mapping, and the private runbook
# tree is untracked on purpose.
files="$(git ls-files '*.sh' '*.js' '*.init' \
  | grep -v '^scripts/test-' \
  | grep -v '^tests/' \
  | grep -v '^docs/private/' \
  | sort)"

{
  printf '# Function index\n\n'
  # Literal markdown backticks, not command substitution.
  # shellcheck disable=SC2016
  printf 'Generated by `scripts/gen-index.sh`; `scripts/check-index.sh` fails when it\n'
  printf 'is stale. Grep it rather than reading it:\n\n'
  printf '```\n'
  printf 'grep -n <function name> docs/INDEX.md\n'
  printf '```\n\n'
  # Literal markdown backticks, not command substitution.
  # shellcheck disable=SC2016
  printf 'Each entry is `line  name  - purpose`, where the purpose is the first line of\n'
  printf 'the comment above the function. Files under %s lines are omitted: reading\n' "$min_lines"
  printf 'those whole is cheap enough.\n'
} >"$out.new"

for file in $files; do
  lines="$(wc -l <"$file" | tr -d ' ')"
  [ "$lines" -ge "$min_lines" ] || continue
  awk -v file="$file" -v lines="$lines" '
		# Remember the most recent comment block so a definition can claim it.
		/^[[:space:]]*(#|\/\/)/ {
			text = $0
			sub(/^[[:space:]]*(#|\/\/)[[:space:]]?/, "", text)
			if (!in_comment) { first = text; in_comment = 1 }
			next
		}
		{
			name = ""
			if (match($0, /^[A-Za-z_][A-Za-z0-9_]*\(\)[[:space:]]*\{/))
				name = substr($0, 1, index($0, "(") - 1)
			else if (match($0, /^[[:space:]]*function[[:space:]]+[A-Za-z_$][A-Za-z0-9_$]*[[:space:]]*\(/)) {
				name = $0
				sub(/^[[:space:]]*function[[:space:]]+/, "", name)
				sub(/[[:space:]]*\(.*$/, "", name)
			}
			if (name != "") {
				purpose = in_comment ? first : ""
				if (length(purpose) > 78) purpose = substr(purpose, 1, 75) "..."
				if (!printed) {
					printf "\n## %s - %s lines\n\n", file, lines
					printed = 1
				}
				if (purpose != "")
					printf "%s  %s  - %s\n", NR, name, purpose
				else
					printf "%s  %s\n", NR, name
			}
			in_comment = 0
		}
	' "$file" >>"$out.new"
done

mv "$out.new" "$out"
printf 'wrote %s (%s lines)\n' "${out#"$root"/}" "$(wc -l <"$out" | tr -d ' ')"
